// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmX2dFAWQlgpytjoFnO0kMcrhf7bHtNq8',
    appId: '1:848463368438:web:693667e61a01ded9441cd7',
    messagingSenderId: '848463368438',
    projectId: 'paikarishop-b4da6',
    authDomain: 'paikarishop-b4da6.firebaseapp.com',
    storageBucket: 'paikarishop-b4da6.firebasestorage.app',
    measurementId: 'G-380G4ZWX58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7n3-NshGDSRwbTTrtthhYs7C3RxWfr80',
    appId: '1:848463368438:android:77247d7289824529441cd7',
    messagingSenderId: '848463368438',
    projectId: 'paikarishop-b4da6',
    storageBucket: 'paikarishop-b4da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0u1NUElA2UZ_9qQWF9X03u-Ry52MBjFU',
    appId: '1:848463368438:ios:d79f8cc16a7cc2fc441cd7',
    messagingSenderId: '848463368438',
    projectId: 'paikarishop-b4da6',
    storageBucket: 'paikarishop-b4da6.firebasestorage.app',
    iosBundleId: 'com.example.paikariShop',
  );
}
